---
#CustomJoFt (Custom Join Left Message) Settings
#Usage {name} to show player Name!

#Join Message, Set To False To Disable
join-message: "§f[§a+§f] §a{name}"

#Join Title, Set To False To Disable
join-title: "§l§eWelcome {name}!"

#Join SubTitle, Set To False To Disable
join-subtitle: false

#Left Message, Set To False To Disable
left-message: "§f[§c-§f] §c{name}"
  
#Guardian Effect, Set To False To Disable
guardian-effect: true
...
